In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\Dev\Downloads\airbnb_cleaned_dataset (2).csv")

In [4]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101707 entries, 0 to 101706
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              101707 non-null  int64
 1   host id                         101707 non-null  int64
 2   host_identity_verified          101707 non-null  object
 3   neighbourhood group             101683 non-null  object
 4   neighbourhood                   101707 non-null  object
 5   lat                             101707 non-null  float64
 6   long                            101707 non-null  float64
 7   country                         101707 non-null  object
 8   country code                    101707 non-null  object
 9   instant_bookable                101707 non-null  bool
 10  cancellation_policy             101707 non-null  object
 11  room type                       101707 non-null  object
 12  Construction year               101707 non-null  int64
 13  price_in_dollar                 101707 non-null  int64
 14  service fee in $                101707 non-null  int64
 15  minimum nights                  101707 non-null  int64
 16  number of reviews               101707 non-null  int64
 17  last review                     85923 non-null   object
 18  reviews per month               101707 non-null  float64
 19  review rate number              101707 non-null  int64
 20  calculated host listings count  101707 non-null  int64
 21  availability 365                101707 non-null  int64
dtypes: bool(1), float64(3), int64(10), object(8)
memory usage: 16.4+ MB

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,...,Construction year,price_in_dollar,service fee in $,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,80014485718,Not Verified,Brooklyn,Kensington,40.65,-73.97,United States,US,False,...,2020,966,193,10,9,2021-10-19,0.21,4,6,286
1,1002102,52335172823,Verified,Manhattan,Midtown,40.75,-73.98,United States,US,False,...,2007,142,28,30,45,2022-05-21,0.38,4,2,228
2,1002403,78829239556,Verified,Manhattan,Harlem,40.81,-73.94,United States,US,True,...,2005,620,124,3,0,NaN,0.00,5,1,352
3,1002755,85098326012,Not Verified,Brooklyn,Clinton Hill,40.69,-73.96,United States,US,True,...,2005,368,74,30,270,2019-05-07,4.64,4,1,322
4,1003689,92037596077,Verified,Manhattan,East Harlem,40.80,-73.94,United States,US,False,...,2009,204,41,10,9,2018-11-19,0.10,3,1,289

In [5]:
print(df.columns)
num = [ 'lat', 'long','price_in_dollar', 'service fee in $',
       'minimum nights', 'number of reviews',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365']

Index(['id', 'host id', 'host_identity_verified', 'neighbourhood group',
       'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price_in_dollar', 'service fee in $',
       'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365'],
      dtype='object')

In [6]:
def stat(x, df):
    # If x is row index (integer), use iloc
    subset = df.loc[:,x]
    
    mean_val = np.mean(subset)
    var_val  = np.var(subset)
    min_val  = np.min(subset)
    max_val  = np.max(subset)
    
    stats = pd.DataFrame({
        'Mean': [mean_val],
        'Var': [var_val],
        'Min': [min_val],
        'Max': [max_val]
    })
    
    return stats

# REVIEWING EACH COLUMN

In [7]:
df.iloc[:,0]
df.iloc[:,0] = df.iloc[:,0].astype(str)
df.iloc[:,0].describe()

C:\Users\Dev\AppData\Local\Temp\ipykernel_9156\1221526592.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0          1001254
1          1002102
2          1002403
3          1002755
4          1003689
            ...
101702    57365208
101703    57365760
101704    57366313
101705    57366865
101706    57367417
Name: id, Length: 101707, dtype: object' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,0] = df.iloc[:,0].astype(str)

count      101707
unique     101707
top       1001254
freq            1
Name: id, dtype: object

In [8]:
df.iloc[:,1]
df.iloc[:,1] = df.iloc[:,1].astype(str)
df.iloc[:,1].describe()

C:\Users\Dev\AppData\Local\Temp\ipykernel_9156\984207553.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0         80014485718
1         52335172823
2         78829239556
3         85098326012
4         92037596077
             ...
101702    77326652202
101703    45936254757
101704    23801060917
101705    15593031571
101706    93578954226
Name: host id, Length: 101707, dtype: object' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,1] = df.iloc[:,1].astype(str)

count          101707
unique         101706
top       29531702698
freq                2
Name: host id, dtype: object

In [9]:
df.iloc[:,2]
df.iloc[:,2].value_counts()
df.iloc[:,2].describe()

count           101707
unique               2
top       Not Verified
freq             50906
Name: host_identity_verified, dtype: object

In [10]:
df.iloc[:,3]
df.iloc[:,3].value_counts()
# neighbourhood group
# Manhattan        43420
# Brooklyn         41471
# Queens           13164
# Bronx             2684
# Staten Island      943
# brookln              1
# Name: count, dtype: int64


df.loc[df['neighbourhood group'] == 'brookln', 'neighbourhood group'] = 'Brooklyn'

df.iloc[:,3].value_counts()
# df.iloc[:,3].describe()

neighbourhood group
Manhattan        43420
Brooklyn         41472
Queens           13164
Bronx             2684
Staten Island      943
Name: count, dtype: int64

In [11]:
df.iloc[:,4]
df.iloc[:,4].value_counts()
df.iloc[:,4].isna().sum()
df.iloc[:,4].info()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: neighbourhood
Non-Null Count   Dtype
--------------   -----
101707 non-null  object
dtypes: object(1)
memory usage: 794.7+ KB

In [12]:
df.iloc[:,5]
df.iloc[:,5].info()
stat('lat',df)
df.iloc[:,5].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: lat
Non-Null Count   Dtype
--------------   -----
101707 non-null  float64
dtypes: float64(1)
memory usage: 794.7 KB

np.int64(0)

In [13]:
df.iloc[:,6]
df.iloc[:,6].info()
stat('long',df)
df.iloc[:,6].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: long
Non-Null Count   Dtype
--------------   -----
101707 non-null  float64
dtypes: float64(1)
memory usage: 794.7 KB

np.int64(0)

In [14]:
df.iloc[:,7]
df.iloc[:,7].info()
# stat('country',df)
df.iloc[:,7].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: country
Non-Null Count   Dtype
--------------   -----
101707 non-null  object
dtypes: object(1)
memory usage: 794.7+ KB

np.int64(0)

In [15]:
df.iloc[:,8]
# df.iloc[:,7].info()
# stat('country',df)
df.iloc[:,8].isna().sum()

np.int64(0)

In [16]:
df.iloc[:,9]
df.iloc[:,9].info()
# # stat('country',df)
df.iloc[:,9].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: instant_bookable
Non-Null Count   Dtype
--------------   -----
101707 non-null  bool
dtypes: bool(1)
memory usage: 99.5 KB

np.int64(0)

In [17]:
df.iloc[:,10]
df.iloc[:,10].info()
df.iloc[:,10].value_counts()
# stat('country',df)
df.iloc[:,10].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: cancellation_policy
Non-Null Count   Dtype
--------------   -----
101707 non-null  object
dtypes: object(1)
memory usage: 794.7+ KB

np.int64(0)

In [18]:
df.iloc[:,11]
df.iloc[:,11].info()
df.iloc[:,11].value_counts()
# stat('country',df)
df.iloc[:,11].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: room type
Non-Null Count   Dtype
--------------   -----
101707 non-null  object
dtypes: object(1)
memory usage: 794.7+ KB

np.int64(0)

In [19]:
df.iloc[:,12]
df['Construction year'] = pd.to_datetime(df['Construction year'])
df.iloc[:,12].info()
df.iloc[:,12].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: Construction year
Non-Null Count   Dtype
--------------   -----
101707 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 794.7 KB

np.int64(0)

In [20]:
df.iloc[:,13]
df.iloc[:,13].info()
df.iloc[:,13].isna().sum()
df.iloc[:,13].describe()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: price_in_dollar
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

count    101707.000000
mean        623.817702
std         332.690973
min           0.000000
25%         337.000000
50%         623.000000
75%         912.000000
max        1200.000000
Name: price_in_dollar, dtype: float64

In [21]:
df.iloc[:,14]
df.iloc[:,14].info()
df.iloc[:,14].isna().sum()
df.iloc[:,14].describe()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: service fee in $
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

count    101707.000000
mean        124.695154
std          66.555511
min           0.000000
25%          67.000000
50%         124.000000
75%         182.000000
max         240.000000
Name: service fee in $, dtype: float64

In [22]:
df.iloc[:,15]
df.iloc[:,15].info()
df.iloc[:,15].isna().sum()
df.iloc[:,15].describe()
# count    101707.000000
# mean          8.085215
# std          30.526226
# min       -1223.000000
# 25%           1.000000
# 50%           3.000000
# 75%           5.000000
# max        5645.000000
# Name: minimum nights, dtype: float64

np.percentile(df.iloc[:,15],90)              # Checked on multiple percentiles like 30,40,50,...,98
np.percentile(df.iloc[:,15],99)               # 99th percentile = 50
np.percentile(df.iloc[:,15],1)               # 99th percentile = 1

df.loc[df.loc[:,'minimum nights'] < 0 ,"minimum nights"]

# 127       -10
# 317        -1
# 329       -10
# 349       -12
# 379        -2
# 421        -3
# 42215   -1223         
# 42269    -365
# 42307    -200      
# 69481    -125
# 90939     -10
# 91025     -10
#Deleting them 
df.drop(index=df.loc[df.loc[:,'minimum nights'] < 0 ,"minimum nights"].index)

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: minimum nights
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,...,Construction year,price_in_dollar,service fee in $,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,80014485718,Not Verified,Brooklyn,Kensington,40.65,-73.97,United States,US,False,...,1970-01-01 00:00:00.000002020,966,193,10,9,2021-10-19,0.21,4,6,286
1,1002102,52335172823,Verified,Manhattan,Midtown,40.75,-73.98,United States,US,False,...,1970-01-01 00:00:00.000002007,142,28,30,45,2022-05-21,0.38,4,2,228
2,1002403,78829239556,Verified,Manhattan,Harlem,40.81,-73.94,United States,US,True,...,1970-01-01 00:00:00.000002005,620,124,3,0,NaN,0.00,5,1,352
3,1002755,85098326012,Not Verified,Brooklyn,Clinton Hill,40.69,-73.96,United States,US,True,...,1970-01-01 00:00:00.000002005,368,74,30,270,2019-05-07,4.64,4,1,322
4,1003689,92037596077,Verified,Manhattan,East Harlem,40.80,-73.94,United States,US,False,...,1970-01-01 00:00:00.000002009,204,41,10,9,2018-11-19,0.10,3,1,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101702,57365208,77326652202,Not Verified,Brooklyn,Flatbush,40.65,-73.96,United States,US,True,...,1970-01-01 00:00:00.000000000,696,0,7,12,2019-03-27,0.44,5,1,0
101703,57365760,45936254757,Verified,Brooklyn,Bushwick,40.70,-73.93,United States,US,False,...,1970-01-01 00:00:00.000000000,909,0,1,19,2017-08-31,0.72,3,2,0
101704,57366313,23801060917,Verified,Brooklyn,Bedford-Stuyvesant,40.68,-73.91,United States,US,True,...,1970-01-01 00:00:00.000000000,387,0,2,50,2019-06-26,3.12,4,2,235
101705,57366865,15593031571,Not Verified,Manhattan,Harlem,40.81,-73.94,United States,US,True,...,1970-01-01 00:00:00.000000000,848,0,2,0,NaN,0.00,1,1,0
101706,57367417,93578954226,Verified,Manhattan,Harlem,40.81,-73.95,United States,US,False,...,1970-01-01 00:00:00.000002011,1128,0,4,22,2019-06-15,0.85,4,1,238

In [23]:
len(df.loc[df.loc[:,'minimum nights'] > 90 ,"minimum nights"])

df.loc[df.loc[:,'minimum nights'] > 90 ,"minimum nights"].index
df.drop(index=df.loc[df.loc[:,'minimum nights'] > 90 ,"minimum nights"].index)

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,...,Construction year,price_in_dollar,service fee in $,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,80014485718,Not Verified,Brooklyn,Kensington,40.65,-73.97,United States,US,False,...,1970-01-01 00:00:00.000002020,966,193,10,9,2021-10-19,0.21,4,6,286
1,1002102,52335172823,Verified,Manhattan,Midtown,40.75,-73.98,United States,US,False,...,1970-01-01 00:00:00.000002007,142,28,30,45,2022-05-21,0.38,4,2,228
2,1002403,78829239556,Verified,Manhattan,Harlem,40.81,-73.94,United States,US,True,...,1970-01-01 00:00:00.000002005,620,124,3,0,NaN,0.00,5,1,352
3,1002755,85098326012,Not Verified,Brooklyn,Clinton Hill,40.69,-73.96,United States,US,True,...,1970-01-01 00:00:00.000002005,368,74,30,270,2019-05-07,4.64,4,1,322
4,1003689,92037596077,Verified,Manhattan,East Harlem,40.80,-73.94,United States,US,False,...,1970-01-01 00:00:00.000002009,204,41,10,9,2018-11-19,0.10,3,1,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101702,57365208,77326652202,Not Verified,Brooklyn,Flatbush,40.65,-73.96,United States,US,True,...,1970-01-01 00:00:00.000000000,696,0,7,12,2019-03-27,0.44,5,1,0
101703,57365760,45936254757,Verified,Brooklyn,Bushwick,40.70,-73.93,United States,US,False,...,1970-01-01 00:00:00.000000000,909,0,1,19,2017-08-31,0.72,3,2,0
101704,57366313,23801060917,Verified,Brooklyn,Bedford-Stuyvesant,40.68,-73.91,United States,US,True,...,1970-01-01 00:00:00.000000000,387,0,2,50,2019-06-26,3.12,4,2,235
101705,57366865,15593031571,Not Verified,Manhattan,Harlem,40.81,-73.94,United States,US,True,...,1970-01-01 00:00:00.000000000,848,0,2,0,NaN,0.00,1,1,0
101706,57367417,93578954226,Verified,Manhattan,Harlem,40.81,-73.95,United States,US,False,...,1970-01-01 00:00:00.000002011,1128,0,4,22,2019-06-15,0.85,4,1,238

In [24]:
df = df.reset_index(drop=True)

In [25]:
df.iloc[:,16]
df.iloc[:,16].info()
df.iloc[:,16].isna().sum()
df.iloc[:,16].describe()
np.percentile(df.iloc[:,16],90)              # Checked on multiple percentiles like 30,40,50,...,98
np.percentile(df.iloc[:,16],100)               # 99th percentile = 112

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: number of reviews
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

np.float64(1024.0)

In [26]:
df.iloc[:,17]
df.iloc[:,17].info()
df.iloc[:,17].isna().sum()
df.loc[df.iloc[:,17].isna(),'last review'] = "No review"
df.iloc[:,17].isna().sum()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: last review
Non-Null Count  Dtype
--------------  -----
85923 non-null  object
dtypes: object(1)
memory usage: 794.7+ KB

np.int64(0)

In [27]:
df.iloc[:,18]
df.iloc[:,18].info()
df.iloc[:,18].isna().sum()
df.iloc[:,18].describe()



df[df.iloc[:,18] >= 90 ]

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: reviews per month
Non-Null Count   Dtype
--------------   -----
101707 non-null  float64
dtypes: float64(1)
memory usage: 794.7 KB

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,...,Construction year,price_in_dollar,service fee in $,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
49422,28424688,20032806094,Verified,Manhattan,Theater District,40.76,-73.98,United States,US,False,...,1970-01-01 00:00:00.000002008,89,18,1,849,2022-03-03,90.0,4,12,361

In [28]:
df.iloc[:,19]
df.iloc[:,19].info()
df.iloc[:,19].isna().sum()
df.iloc[:,19].describe()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: review rate number
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

count    101707.000000
mean          3.269362
std           1.295171
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           5.000000
Name: review rate number, dtype: float64

In [29]:
df.iloc[:,20]
df.iloc[:,20].info()
df.iloc[:,20].isna().sum()
df.iloc[:,20].describe()


df[df.iloc[:,20] > 100 ]

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: calculated host listings count
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

,id,host id,host_identity_verified,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,...,Construction year,price_in_dollar,service fee in $,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
9590,6381290,50445710041,Not Verified,Manhattan,Financial District,40.71,-74.01,United States,US,False,...,1970-01-01 00:00:00.000002022,381,76,30,3,2018-07-12,0.09,5,121,350
9925,6566311,70482716359,Not Verified,Manhattan,Theater District,40.76,-73.99,United States,US,True,...,1970-01-01 00:00:00.000002005,80,16,30,0,No review,0.00,1,121,175
10185,6709909,12065491073,Verified,Manhattan,Theater District,40.76,-73.99,United States,US,False,...,1970-01-01 00:00:00.000002016,244,49,30,0,No review,0.00,2,121,422
10248,6744704,12672637361,Verified,Manhattan,Midtown,40.77,-73.98,United States,US,False,...,1970-01-01 00:00:00.000002011,789,158,30,0,No review,0.00,2,121,330
10340,6795515,34609745113,Verified,Manhattan,Chelsea,40.74,-73.99,United States,US,True,...,1970-01-01 00:00:00.000002009,222,44,30,3,2017-12-31,0.07,2,121,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98709,55709965,82511783691,Not Verified,Queens,Elmhurst,40.74,-73.87,United States,US,False,...,1970-01-01 00:00:00.000002013,311,62,30,1,2019-10-03,0.25,2,103,252
98850,55790048,64135827752,Not Verified,Manhattan,East Village,40.72,-73.98,United States,US,True,...,1970-01-01 00:00:00.000002022,593,119,30,0,No review,0.00,3,232,330
99047,55898851,29296373343,Verified,Queens,Astoria,40.77,-73.92,United States,US,False,...,1970-01-01 00:00:00.000002006,865,173,30,0,No review,0.00,4,103,237
99419,56104307,94442650453,Not Verified,Manhattan,Hell's Kitchen,40.76,-74.00,United States,US,False,...,1970-01-01 00:00:00.000002020,68,14,30,2,2017-09-17,0.08,2,121,365
99474,56134684,55402944864,Not Verified,Manhattan,Hell's Kitchen,40.77,-73.98,United States,US,True,...,1970-01-01 00:00:00.000002014,538,108,30,1,2018-01-21,0.06,2,121,345

In [30]:
df.iloc[:,21]
df.iloc[:,21].info()
df.iloc[:,21].isna().sum()
df.iloc[:,21].describe()


df['availability 365'][df.iloc[:,21] <0 ]
# 103     -10
# 106      -2
# 173      -6
# 229      -9
# 274      -9
#          ..
# 86347    -7
# 86407    -4
# 86436    -2
# 86462    -7
# 86525    -7
df.loc[df.iloc[:,21] <0 , 'availability 365'] =  df['availability 365'][df.iloc[:,21] <0 ] * (-1)


df.iloc[:,21].clip(lower=0,upper=365,inplace=True)
df.iloc[:,21].describe()

<class 'pandas.core.series.Series'>
RangeIndex: 101707 entries, 0 to 101706
Series name: availability 365
Non-Null Count   Dtype
--------------   -----
101707 non-null  int64
dtypes: int64(1)
memory usage: 794.7 KB

C:\Users\Dev\AppData\Local\Temp\ipykernel_9156\199926563.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.iloc[:,21].clip(lower=0,upper=365,inplace=True)

count    101707.000000
mean        139.595180
std         133.451356
min           0.000000
25%           3.000000
50%          95.000000
75%         268.000000
max         365.000000
Name: availability 365, dtype: float64

In [31]:
df.iloc[:,3].isna().sum()
df.dropna(subset=['neighbourhood group'], inplace=True)

In [34]:
df = df.reset_index(drop=True)
df
df.to_csv('cleaned_&_filled_airbnb_data.csv', index=False)